# Generated by Django 2.2.16 on 2020-11-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcelular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
