# Generated by Django 2.2.16 on 2020-11-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcelular', '0002_auto_20201101_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
